name: twitter_clone
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  appwrite: ^9.0.0
  flutter_riverpod: ^2.3.6
  flutter_svg: ^2.0.5
  fpdart: ^0.5.0
  image_picker: ^0.8.7+4
  carousel_slider: ^4.2.1
  timeago: ^3.4.0
  any_link_preview: ^3.0.0
  like_button: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/svgs/
